// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package database

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Feedback struct {
	ID        int32            `json:"id"`
	UserID    pgtype.Int4      `json:"user_id"`
	Message   string           `json:"message"`
	CreatedAt pgtype.Timestamp `json:"created_at"`
}

type LearnContent struct {
	ID        int32       `json:"id"`
	Category  string      `json:"category"`
	Title     string      `json:"title"`
	Content   string      `json:"content"`
	VideoUrl  pgtype.Text `json:"video_url"`
	SortOrder pgtype.Int4 `json:"sort_order"`
}

type Session struct {
	ID             int32            `json:"id"`
	UserID         pgtype.Int4      `json:"user_id"`
	SessionNumber  int32            `json:"session_number"`
	Date           pgtype.Date      `json:"date"`
	FocusType      string           `json:"focus_type"`
	PlannedWarmup  []byte           `json:"planned_warmup"`
	PlannedMain    []byte           `json:"planned_main"`
	PlannedProject []byte           `json:"planned_project"`
	CreatedAt      pgtype.Timestamp `json:"created_at"`
}

type SessionLog struct {
	ID            int32            `json:"id"`
	SessionID     pgtype.Int4      `json:"session_id"`
	UserID        pgtype.Int4      `json:"user_id"`
	RoutesLogged  []byte           `json:"routes_logged"`
	NewMaxGrade   pgtype.Int4      `json:"new_max_grade"`
	EnergyLevel   pgtype.Int4      `json:"energy_level"`
	SkinCondition pgtype.Text      `json:"skin_condition"`
	Soreness      pgtype.Int4      `json:"soreness"`
	Notes         pgtype.Text      `json:"notes"`
	LoggedAt      pgtype.Timestamp `json:"logged_at"`
}

type User struct {
	ID              int32            `json:"id"`
	Email           string           `json:"email"`
	PasswordHash    string           `json:"password_hash"`
	CurrentMaxGrade int32            `json:"current_max_grade"`
	GoalGrade       int32            `json:"goal_grade"`
	SessionsPerWeek int32            `json:"sessions_per_week"`
	Weaknesses      []byte           `json:"weaknesses"`
	CreatedAt       pgtype.Timestamp `json:"created_at"`
}

type WebSession struct {
	Token  string             `json:"token"`
	Data   []byte             `json:"data"`
	Expiry pgtype.Timestamptz `json:"expiry"`
}
